openapi: 3.0.1
info:
  title: Order Service API
  description: API for managing orders and their items
  version: 1.0.0
servers:
  - url: "{scheme}://{host}/{basePath}"
    variables:
      scheme:
        enum:
          - "https"
          - "http"
        default: "https"
      host:
        default: "camelbee.io"
      basePath:
        default: "/camelbee-service"
paths:
  /orders:
    post:
      summary: Create an order
      operationId: createOrder
      parameters:
        - name: transactionId
          in: header
          required: true
          schema:
            type: string
            format: uuid
        - name: requestId
          in: header
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: Order to add
        required: true
        content:
          application/x-protobuf:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '201':
          description: Order created
          headers:
            transactionId:
              description: Transaction ID
              schema:
                type: string
                format: uuid
            requestId:
              description: Request ID
              schema:
                type: string
                format: uuid
          content:
            application/x-protobuf:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Bad Request
          headers:
            transactionId:
              description: Transaction ID
              schema:
                type: string
                format: uuid
            requestId:
              description: Request ID
              schema:
                type: string
                format: uuid
          content:
            application/x-protobuf:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          headers:
            transactionId:
              description: Transaction ID
              schema:
                type: string
                format: uuid
            requestId:
              description: Request ID
              schema:
                type: string
                format: uuid
          content:
            application/x-protobuf:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Order:
      type: object
      required:
        - salesChannel
      properties:
        id:
          type: string
        salesChannel:
          type: string
        status:
          type: string
          enum:
            - Pending
            - Confirmed
            - Processing
            - Shipped
            - Delivered
            - Completed
            - Canceled
            - Returned
            - Failed
            - On Hold
          description: The status of an order
        orderDate:
          type: string
          description:  Date format is ISO-8601 format (yyyy-MM-dd)
          format: date
        lastUpdateTimestamp:
          type: string
          description: Timestamp in ISO-8601 format (yyyy-MM-ddTHH:mm:ssZ)
          format: date-time
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'

    OrderItem:
      type: object
      required:
        - productName
      properties:
        id:
          type: string
        productId:
          type: string
        productName:
          type: string
        quantity:
          type: integer
        price:
          type: number

    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string

    Orders:
      type: object
      description: A wrapper for a list of orders
      properties:
        order:
          type: array
          items:
            $ref: '#/components/schemas/Order'

