[
  {
    "type": "record",
    "name": "Purchases",
    "namespace": "io.fintech.loan.application.service.model.infra.avro",
    "doc": "A wrapper for a list of purchases",
    "fields": [
      {
        "name": "purchase",
        "type": ["null", {
          "type": "array",
          "items": {
            "type": "record",
            "name": "Purchase",
            "fields": [
              { "name": "id", "type": ["null", "string"], "default": null },
              { "name": "salesChannel", "type": ["null", "string"], "default": null },
              { "name": "status", "type": ["null", "string"], "default": null },
              { "name": "purchaseDate", "type": ["null", "int"], "default": null },
              {  "name": "lastUpdateTimestamp", "type": ["null", "long"], "default": null },
              {
                "name": "items",
                "type": ["null", {
                  "type": "array",
                  "items": {
                    "type": "record",
                    "name": "PurchaseItem",
                    "fields": [
                      { "name": "id", "type": ["null", "string"], "default": null },
                      { "name": "productId", "type": ["null", "string"] },
                      { "name": "productName", "type": ["null", "string"] },
                      { "name": "quantity", "type": ["null", "int"], "default": null },
                      { "name": "price", "type": ["null", "double"], "default": null }
                    ]
                  }
                }],
                "default": null
              }
            ]
          }
        }],
        "default": null
      }
    ]
  },
  {
    "type": "record",
    "name": "Error",
    "namespace": "io.fintech.loan.application.service.model.infra.avro",
    "doc": "Representation of an error",
    "fields": [
      { "name": "code", "type": "string" },
      { "name": "message", "type": "string" }
    ]
  }
]
