<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.camelbee</groupId>
    <artifactId>camelbee-springboot-starter</artifactId>
    <version>3.0.2</version>
  </parent>

  <artifactId>springboot-rest-json</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>springboot-rest-json</name>
  <description>CamelBee mycamelbeeservice API</description>

  <properties>
    <!-- ... -->
  </properties>

  <dependencyManagement>
    <dependencies>
      <!-- ... -->
    </dependencies>
  </dependencyManagement>

  <dependencies>

    <dependency>
      <groupId>org.apache.camel.springboot</groupId>
      <artifactId>camel-mapstruct-starter</artifactId>
    </dependency>


    <dependency>
      <groupId>org.apache.camel.springboot</groupId>
      <artifactId>camel-platform-http-starter</artifactId>
    </dependency>

    <dependency>
      <groupId>org.apache.camel.springboot</groupId>
      <artifactId>camel-rest-openapi-starter</artifactId>
    </dependency>

    <dependency>
      <groupId>org.apache.camel.springboot</groupId>
      <artifactId>camel-http-starter</artifactId>
    </dependency>

    <dependency>
      <groupId>io.swagger.core.v3</groupId>
      <artifactId>swagger-annotations-jakarta</artifactId>
    </dependency>


    <dependency>
      <groupId>net.logstash.logback</groupId>
      <artifactId>logstash-logback-encoder</artifactId>
    </dependency>


  </dependencies>

  <!-- BUILD: Define specific build plugins here -->
  <build>


    <plugins>
      <!-- OpenApi Generator -->
      <plugin>
        <groupId>org.openapitools</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>
        <version>${openapi-generator-maven-plugin.version}</version>
        <executions>
          <!-- Microservice exposes REST api, we need to create camel restconfiguration via rest-openapi and model classes using the order-api.yaml  -->
          <execution>
            <id>generate-rest-sources-api</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <output>${project.build.directory}/generated-sources/openapi</output>
              <inputSpec>${project.basedir}/src/main/resources/openapi/order-api.yaml</inputSpec>
              <generatorName>spring</generatorName>
              <generateApis>false</generateApis>
              <generateSupportingFiles>false</generateSupportingFiles>
              <modelPackage>com.mycompany.model.api.json</modelPackage>
              <configOptions>
                <skipDefaultInterface>true</skipDefaultInterface>
                <useBeanValidation>true</useBeanValidation>
                <sourceFolder>src/main/java</sourceFolder>
                <interfaceOnly>true</interfaceOnly>
                <singleContentTypes>true</singleContentTypes>
                <useTags>true</useTags>
                <oas3>true</oas3>
                <useSpringBoot3>true</useSpringBoot3>
              </configOptions>
            </configuration>
          </execution>


        </executions>
      </plugin>


      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>repackage</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <layers>
            <enabled>true</enabled>
          </layers>
        </configuration>
      </plugin>

    </plugins>
  </build>

  <!-- PROFILES: Define specific profiles here -->
  <profiles>
    <!-- ... -->
  </profiles>

  <!-- REPORTING: Define specific reporting plugins here -->
  <reporting>
    <!-- ... -->
  </reporting>

</project>
